### ISSUE TITLE
Clarify actuator usage

### ISSUE THREAD

**Issue by akeranen** [core-wg/senml-spec#17]
Current text hints that you can use SenML also with actuators, but there is not much details about this yet.

**Comment by nzfarmer1** [comment]
+1 For actuators. But the ability to set any arbitrary value would be preferred - for example the coefficients of an analog sensor, or a flag to initiate a sensor update.

**Comment by fluffy** [comment]
I did not get this into the -03 update but still plan to add it.

**Comment by fluffy** [comment]
I did not get this into the -03 update but still plan to add it.
