### ISSUE TITLE
Ensure we don't base64 encode in CBOR

### ISSUE THREAD

**Issue by fluffy** [core-wg/senml-spec#24]
I think that the current SenML draft is missing a note on JSON/CBOR
differences in Data Value: While it is explicitly stated that vd is a
base64 string in JSON and a binary-value in CBOR, the supposedly
exhaustive list of differences in 6. fails to mention that no base64
encoding is done in CBOR. Suggested addition:

o For Data Values, no base64url-encoding is done, as the data can be
 directly expressed as binary-value.

Furthermore, I suggest that "Characters in the Data Value are base64
encoded" be expressed as "Bytes [...]" or "Octets are encoded [...]", to
make the distinction to the character-based strings and binary data
clearer. (The only context in which I'd name bytes of binary data
"Character" are when speaking of a "char" in C).

Best regards
Christian

**Comment by cabo** [comment]
Indeed, characters should be called characters, and bytes should be called bytes.
(In C, bytes are represented as uint8_t :-).

s/can be/are/ (they are!)

**Comment by fluffy** [comment]
Have a read of the PR I put in for this. I think it resolves the issue

**Comment by akeranen** [comment]
Looks good to me (with the one typo fix)
