### ISSUE TITLE
SI units vs. prefixes

### ISSUE THREAD

**Issue by cabo** [core-wg/senml-spec#4]
The SI unit for mass is kg.

12.1 says:

> `4.` Use of SI prefixes such as "k" before the unit is not allowed.  Instead one
>   can represent the value using scientific notation such a 1.2e3. TODO - Open
>   Issue. Some people would like to have SI prefixes to improve human
>   readability. 

That leads to being unable to use the SI unit for mass, instead, we are using g.
But then we are using derived units such as l (dm3) and l/s (dm3/s).

So:
1. We need to decide the above TODO.
2. We need to decide whether to stick with SI units or allow simple names for derived units (gram, minute, liter).

Domain-specific units are often weird (1/min = "rpm", mmHg or mol/dl in medicine, ...).

**Comment by fluffy** [comment]
I think a key part of the registry vs existing SI unit tables was to be able to use things that were not proper units but agree things can be cleaned up. Clearly rpm and bpm have the same unit in the sense of what the dimensions are but what they are used to measure are pretty different and knowing that it is bpm often provides a level of information about how to process the information. As related to our whole conversation on why we needed the IANA table, the ability to have things in this that are not really a classic SI unit is the key value of SenML. The rules are just guidelines. If we want to change the unit of mass from g to kg, we can do that but the point on the prefixes was not to have both g and kg as that just reduces interoperability
