### ISSUE TITLE
Travis Support [not draft related]

### ISSUE THREAD

**Issue by jaimejim** [core-wg/senml-spec#41]
At the moment it fails to compile on travis, so you might want to have a look at it.
https://travis-ci.org/core-wg/senml-spec

**Comment by fluffy** [comment]
Cisco legal will not allow me to run the default make gh_pages on this project which is the reasons it does not have a ghpages branch of the travis scripts to make them. Please please please make changes like this as a PR so we can review them before checking them in. Glad to explain the longer version of this in person but it involves patents.

**Comment by fluffy** [comment]
(On side note, I've got no problem with fixing up things to make it so travis can build the draft but a some work needed to do this to make sure all the tools get installed to be able to build the example files).
