### ISSUE TITLE
Questionable units

### ISSUE THREAD

**Issue by cabo** [core-wg/senml-spec#5]
The following units are questionable:
- % -- this looks like a percentage (0..100), but it is not (0..1).
- count -- what?  This is about a dimensionless quantity?
- %RH, %EL appear to be percentages, but imply a quantity.
- EL may be a quantity, but the unit is second.  In SI, we don't do new units for new quantities (there is no "millimeter radius" or "nanometer wavelength").
- Bspl -- this really should be in dB (see #4), SPL is the quantity again.
- beat/min, beats -- these should be 1/min (but see #4) and 1 (dimensionless); how is beats different from count?

We don't have bit (but bit/s), byte.  1/min is there only for heartbeats, not for revolutions ("rpm").  Should really be 1/s (but see #4).  lat and lon are a bit weird, too.

(Celsius is also questionable -- the rationale of #4 should call for all measurements being expressed in Kelvin.)

**Comment by fluffy** [comment]
on on kevin vs C, every thermostat manufacture I can find has said they want C over kelvin. 

bunch of implementation are using 0 to 1 for light levels but imagine we could change % to 0 to 100 

count - yep count :-) Bunch of sensors simply count pulses of who knows what. Totally agree this is not a unit but this is the pragmatic sort of thing needed 

EL is a great example of something that many sensors in sports have to deal with in common way. They use this and it works well for them

**Comment by cabo** [comment]
So I changed % to mean percentage.  Cel of course stays in (even though it is wrong wrong wrong :-).
I have marked count and EL with the "not so recommended for new producers" range.  But we don't really have a base unit for "1" (dimensionless) either.  The problem remains that giving a unit doesn't tell you what quantity actually has been measured, and the trend to make more and more finer grained units for the same kinds quantities measured in different ways (as in psi vs. psig etc.) leads into the woods.

**Comment by fluffy** [comment]
just finding all the email now … 

I think the thing that people like about this is it’s not a SI unit, it’s something that tells you something useful about what you are measuring across a wide range of devices. I think we need to think of these from a point of view of broadly useful than are they a SI unit. Agree with your slippery slope psi, psig, etc argument but all of those exist for a reason.
