### ISSUE TITLE
Typo in some Base Name examples

### ISSUE THREAD

**Issue by mojotalantikite** [core-wg/senml-spec#56]
There seems to be occasional typos where semicolons are inserted in some of the example json base names. For example, notice the "bn" in ex3.json:
```
[{"bn": "urn:dev:ow:10e2073a0108006;",
  "bt": 1276020076.001,
  "bu": "A",
  "bver": 5,
  "n": "voltage", "u": "V", "v": 120.1 },
   { "n": "current", "t": -5, "v": 1.2 },
   { "n": "current", "t": -4, "v": 1.30 },
   { "n": "current", "t": -3, "v": 0.14e1 },
   { "n": "current", "t": -2, "v": 1.5 },
   { "n": "current", "t": -1, "v": 1.6 },
   { "n": "current", "t": 0,  "v": 1.7 } 
]
```
I'm assuming it's just a typo since ";" seems to not be allowed in resulting concatenated names. Happy to fix this in the places that I've found and submit a PR if you'd like.

**Comment by fluffy** [comment]
Thanks for catching that. Would be great if you send a PR but I will fix this at some point either way.

**Comment by fluffy** [comment]
Fixed this - thanks
