### ISSUE TITLE
Clarify name character set restrictions

### ISSUE THREAD

**Issue by akeranen** [core-wg/senml-spec#73]
From Peter's review: 

>>> Please note that this set is more restricted than the range of 
characters allowed for URIs in general (RFC 3986) or URNs in
particular (RFC 8141). At the least it would be helpful to point
this out, because AFAICS it will limit the URI schemes or URN
namespaces that can be used.

>> Good point. I'd suggest text:

>> "Note that the character set for SenML names is a subset of the
characters allowed in URIs. The restricted set was chosen to enable
efficient and safe use of names in various systems (e.g., as database
keys)."

> I suggest that we also say something like "The restrictions imply that
care needs to be taken in the choice of URIs or URNs as SenML names."
Furthermore, if someone wants to use a URI scheme that allows characters
outside that set (e.g., the 'tag' scheme), then do those characters need
to be encoded somehow? (Ick.) If not, then we should say so.

One should not try to put "full URIs" into the names. Rather the names can be used as part of a URI. Perhaps something we should be more clear about.

**Comment by akeranen** [comment]
Also ABNF of the set

**Comment by akeranen** [comment]
Clarify that dev:urn URIs are OK because they match the charset

**Comment by fluffy** [comment]
so I think we have dealt with this and can close it.

**Comment by akeranen** [comment]
Peter's proposal for updated text is here: https://www.ietf.org/mail-archive/web/core/current/msg08899.html
The PR #85 applies the new text with slight modifications.
