### ISSUE TITLE
Message size rationale

### ISSUE THREAD

**Issue by akeranen** [core-wg/senml-spec#74]
>> Why was 80 bytes chosen instead of, say, 50 bytes or 64 bytes or
100 bytes? (Here again I'd remove the text about mesh networks.)

> These two points, mesh and 80 bytes, are related. 802.15.4 (6LoWPAN)
mesh networks result in about 80 bytes of usable payload per packet
without fragmentation.

How about we say keeping it small is good and quote examples of 802.15.4 has about 80 byte payload and  that LoRa has 51 byte of applications payload in long range mode and just remove any reference to "mesh"

**Comment by fluffy** [comment]
I'm fine with suggestion above. I'm also fine with just leaving draft as is.

**Comment by akeranen** [comment]
Addressed by PR #86
