### ISSUE TITLE
Links extension in base spec or separate doc?

### ISSUE THREAD

**Issue by akeranen** [core-wg/senml-spec#76]
From WGLC announcement:
> One question that we also want to decide in this WGLC is whether to keep the link extension in this Proposed-Standard-to-be, or whether it merits its own document.  It is not in the same state of completion as the rest of the document, and it has served a bit of its purpose making sure that the extension mechanism is in place and can be used.  It’s just that the extension itself may not yet be ready for prime time, and it may become better from spending a bit more time in a separate document.

**Comment by fluffy** [comment]
The key thing is the "l" gets a 9 reserved for it in in cbor and simular in EXI schema. I think how it is in current draft is fine.

**Comment by akeranen** [comment]
@fluffy We discussed at the last CoRE meeting that it's fine that "l" doesn't get CBOR label. You would anyway save just a single byte with that and the links tend to be quite many bytes so there isn't much saving to be achieved. Not sure if that's an issue for EXI schema though?

**Comment by fluffy** [comment]
It's makes about as much difference for EXI as CBOR so I would not worry about it. Happy to go with whatever got decided at last meeting.
